In [1]:
import numpy as np
import pandas as pd

file name -> Columns

quater-i.csv -> ['order_id', 'quantity', 'item_id', 'choice_description_id' 'item_price']

items.csv -> ['item_id', 'item_name']

In [2]:
# import like this
items_path = "../Datasets/items.csv"
q1_path = "../Datasets/quarter-1.csv"
q2_path = "../Datasets/quarter-2.csv"
q3_path = "../Datasets/quarter-3.csv"


q1= pd.read_csv(q1_path)
q2 = pd.read_csv(q2_path)
q3 = pd.read_csv(q3_path)

items = pd.read_csv(items_path)

### `Q:1-5`
1. You are given three quater files, your job is to append these three files and make a single dataframe.
2. Have a index as Q-1 Q-2 Q-3 for respective quater files in the dataframe
3. Your are given a file items.csv which has item_id and item_name. Find out most sold items in each quarter.
4. Find out items which has made most revenue in each quarter.
5. Find out avg order price of each quarter.

***Note: item_price is given as str with $ sign, in earlier task you have converted this to rupees, here too first convert item_price field in rupees.***

In [3]:
# Q1 and Q2
print("q1 shape: ", q1.shape)
print("q2 shape: ", q2.shape)
print("q3 shape: ", q3.shape)
df_append=pd.concat([q1, q2, q3], ignore_index=False,keys=["q1", "q2", "q3"])
df_append

q1 shape:  (2275, 5)
q2 shape:  (2347, 5)
q3 shape:  (0, 5)

        order_id quantity item_id choice_description_id item_price
q1 0           1        1       1                     1     $3.39
   1           1        1       2                     2     $3.39
   2           2        2       4                     3    $16.98
   3           4        1       7                     6     $9.25
   4           6        1       9                     8     $8.75
...          ...      ...     ...                   ...        ...
q2 2342     1829        1      23                    92    $11.25
   2343     1830        1      23                  1043    $11.25
   2344     1832        1      10                   116     $8.75
   2345     1832        1       8                     0     $4.45
   2346     1834        1      20                   515    $11.25

[4622 rows x 5 columns]

In [4]:
# Q3
df_append=df_append.reset_index()
df_append

,level_0,level_1,order_id,quantity,item_id,choice_description_id,item_price
0,q1,0,1,1,1,1,$3.39
1,q1,1,1,1,2,2,$3.39
2,q1,2,2,2,4,3,$16.98
3,q1,3,4,1,7,6,$9.25
4,q1,4,6,1,9,8,$8.75
...,...,...,...,...,...,...,...
4617,q2,2342,1829,1,23,92,$11.25
4618,q2,2343,1830,1,23,1043,$11.25
4619,q2,2344,1832,1,10,116,$8.75
4620,q2,2345,1832,1,8,0,$4.45
4621,q2,2346,1834,1,20,515,$11.25

In [5]:
merge_df=items.merge(df_append, on="item_id", how="inner")
q_df=merge_df.groupby(["level_0","item_name"],as_index=False)["quantity"].sum().sort_values("quantity", ascending=False)
# print(q_df[q_df["level_0"]=="q1"].head(1))
# print(q_df[q_df["level_0"]=="q2"].head(1))
q_df.drop_duplicates(subset=["level_0"], keep="first")

   level_0     item_name quantity
65      q2  Chicken Bowl      394
17      q1  Chicken Bowl      367

In [6]:
merge_df["price"]=merge_df.item_price.apply(lambda x: float(x[1:]))
merge_df

,item_id,item_name,level_0,level_1,order_id,quantity,choice_description_id,item_price,price
0,0,Chips and Fresh Tomato Salsa,q1,11,13,1,0,$2.39,2.39
1,0,Chips and Fresh Tomato Salsa,q1,92,82,1,0,$2.95,2.95
2,0,Chips and Fresh Tomato Salsa,q1,120,104,1,0,$2.95,2.95
3,0,Chips and Fresh Tomato Salsa,q1,163,142,1,0,$2.39,2.39
4,0,Chips and Fresh Tomato Salsa,q1,168,149,1,0,$2.95,2.95
...,...,...,...,...,...,...,...,...,...
4617,48,Veggie Salad,q2,1411,1094,1,755,$8.49,8.49
4618,48,Veggie Salad,q2,1528,1192,1,149,$8.49,8.49
4619,48,Veggie Salad,q2,1605,1263,1,306,$8.49,8.49
4620,48,Veggie Salad,q2,1745,1395,1,755,$8.49,8.49
4621,49,Carnitas Salad,q1,1868,1500,1,940,$8.99,8.99

In [7]:
merge_df["total_price"]=merge_df["quantity"]*merge_df["price"]
merge_df

,item_id,item_name,level_0,level_1,order_id,quantity,choice_description_id,item_price,price,total_price
0,0,Chips and Fresh Tomato Salsa,q1,11,13,1,0,$2.39,2.39,2.39
1,0,Chips and Fresh Tomato Salsa,q1,92,82,1,0,$2.95,2.95,2.95
2,0,Chips and Fresh Tomato Salsa,q1,120,104,1,0,$2.95,2.95,2.95
3,0,Chips and Fresh Tomato Salsa,q1,163,142,1,0,$2.39,2.39,2.39
4,0,Chips and Fresh Tomato Salsa,q1,168,149,1,0,$2.95,2.95,2.95
...,...,...,...,...,...,...,...,...,...,...
4617,48,Veggie Salad,q2,1411,1094,1,755,$8.49,8.49,8.49
4618,48,Veggie Salad,q2,1528,1192,1,149,$8.49,8.49,8.49
4619,48,Veggie Salad,q2,1605,1263,1,306,$8.49,8.49,8.49
4620,48,Veggie Salad,q2,1745,1395,1,755,$8.49,8.49,8.49
4621,49,Carnitas Salad,q1,1868,1500,1,940,$8.99,8.99,8.99

In [8]:
revenue_df=merge_df.groupby(["level_0","item_name"],as_index=False)["total_price"].sum().sort_values("total_price", ascending=False)
revenue_df.drop_duplicates(subset=["level_0"], keep="first")

   level_0     item_name total_price
65      q2  Chicken Bowl     4192.25
17      q1  Chicken Bowl     3852.38

In [9]:
merge_df.groupby(["level_0","order_id"], as_index=False)["total_price"].mean()

     level_0 order_id total_price
0         q1        1        3.39
1         q1        2       33.96
2         q1        4        9.25
3         q1        6        8.75
4         q1        7       11.25
...      ...      ...         ...
2892      q2     1828        4.45
2893      q2     1829       11.25
2894      q2     1830       11.25
2895      q2     1832         6.6
2896      q2     1834       11.25

[2897 rows x 3 columns]

### `Q-6` From the IPL wala dataset you have to find the Purple cap holder each season.

*Note: Bowler with most no wickets in a season gets purple cap. If more than one bowler have same no of wickets in the season, one with least ecomnomy among them is purple cap holder.*

Bowler's Economy = runs-conceded per six ballsum

In [10]:
balls = pd.read_csv("IPL_Ball_by_Ball_2008_2022.csv")
matches = pd.read_csv("IPL_Matches_2008_2022.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'IPL_Ball_by_Ball_2008_2022.csv'

Best bowler in death overs.
Note: Have taken most no of wickets in case of tie with least economy

Death Overs - [16-20]

         bowler  IsBowlerWicket  BowlerRun  IsLegalBall   Economy
91     DJ Bravo             115       2161         1385  9.361733
331  SL Malinga             108       1464         1117  7.863921
53      B Kumar              90       1752         1173  8.961637
148   JJ Bumrah              80       1614         1146  8.450262
339   SP Narine              67       1164          949  7.359326

### `Q-8` Batsman record season wise

Make a function which takes a input `batsman_name` and it returns a dataframe.
Columns of the data frame are - `['Season','Innings', 'TotalRuns', 'Avg', 'HighestScore','StrikeRate']`.
* In result make `Season` column as index.

* Avg - total_runs/ no of time got out. - player_out column will help.
* StrikeRate -(total_runs/ balls faced) * 100- wides are not included in batsman ball faced counts. No balls are included. -> Extra_type column will help
* Batsman Can score runs on No Balls.
* Batsman can get out on No Ball or Wides. And even while being on non-striker. Keep these things in mind before masking.

In [ ]:
# code here
batterdf = seasondf.copy()
batterdf["IsBatsmanBall"] = batterdf["extra_type"].apply(lambda x: 1 if x != "wides" else 0)

def bat_record_season(batsman):
    bdf = batterdf[batterdf.batter == batsman].copy()
    bdf["IsBatsmanOut"] = bdf.batter == bdf.player_out
    df = bdf.groupby(["Season", "ID"], as_index = False)[["batsman_run", "IsBatsmanBall", "IsBatsmanOut"]].sum()
    innings = df.groupby("Season").ID.count()
    df = df.groupby("Season").agg(
    {
        "batsman_run":["sum", "max"],
        "IsBatsmanBall": "sum",
        "IsBatsmanOut": "sum"
    })
    df["Innings"]= innings
    df["TotalRuns"] = df[("batsman_run", "sum")]
    df["Avg"] = df["TotalRuns"] / df[("IsBatsmanOut", "sum")]
    df["HighestScore"] = df[("batsman_run", "max")]
    df["StrikeRate"] = df["TotalRuns"] / df[("IsBatsmanBall", "sum")] * 100
    return df.drop(columns = ["batsman_run", "IsBatsmanBall", "IsBatsmanOut"])
bat_record_season("MS Dhoni")

        Innings TotalRuns         Avg HighestScore  StrikeRate

Season
2007/08      14       414   41.400000           65  133.548387
2009         13       332   41.500000           58  127.203065
2009/10      11       287   31.888889           66  136.666667
2011         13       392   43.555556           70  158.704453
2012         17       358   32.545455           51  128.776978
2013         16       461   46.100000           67  162.897527
2014         15       371   74.200000           57  148.400000
2015         17       372   31.000000           53  121.967213
2016         12       284   40.571429           64  135.238095
2017         15       290   26.363636           61  116.000000
2018         15       455   75.833333           79  150.662252
2019         12       416  104.000000           84  134.627832
2020/21      12       200   25.000000           47  116.279070
2021         11       114   16.285714           18  106.542056
2022         12       232   33.142857           50  123.404255

### `Q-9` Using both dataset, make a dataframe as described below

Data Frame columns-> `['PlayerOfThematch', 'BattingFigure', 'BowlingFigure']`

* BattingFigure->`<runs>/<balls>`
* BowlingFigure->`<wicket>/<runs-conceded>`

DataFrame should have one record for each match.

Say 'V Kohli' got POM award then in dataset include his batting figure of that match. Say he scored 112runs in 76 balls. And he hasn't bowled so Bowling Figure will be NaN
```
PlayerOfThematch BattingFigure BowlingFigure
V Kohli          112/76         nan  

```

In [ ]:
# code here
df = balls.merge(matches[["ID", "Player_of_Match"]], on="ID")
batterdf = df[df.batter == df.Player_of_Match].copy()
batterdf["IsBatsmanBall"] = batterdf["extra_type"].apply(lambda x: 1 if x != "wides" else 0)
batter = batterdf.groupby(["ID", "batter"], as_index=False)[["batsman_run", "IsBatsmanBall"]].sum()
batter["BattingFigure"] = batter[["batsman_run", "IsBatsmanBall"]].apply(lambda x: '/'.join(map(str, x.values)), axis = 1)
batter.rename(columns = {"batter": "PlayerOfMatch"}, inplace = True)
batter.head()

       ID PlayerOfMatch  batsman_run  IsBatsmanBall BattingFigure
0  335982   BB McCullum          158             73        158/73
1  335983    MEK Hussey          116             54        116/54
2  335985    MV Boucher           39             19         39/19
3  335986     DJ Hussey           38             43         38/43
4  335987     SR Watson           76             49         76/49

In [ ]:
bowlerdf = df[df.bowler == df.Player_of_Match].copy()
bowlerdf["IsBowlerWicket"] = bowlerdf["kind"].apply(lambda x: 1 if x in ["caught", 'caught and bowled', 'bowled', 'stumped','lbw', 'hit wicket'] else 0)
bowlerdf["BowlerRun"] = bowlerdf.extra_type.apply(lambda x: 0 if x in ["legbyes", "byes"] else 1) * bowlerdf["total_run"]
bowler = bowlerdf.groupby(["ID", "bowler"], as_index=False)[["IsBowlerWicket", "BowlerRun"]].sum()
bowler["BowlingFigure"] = bowler[["IsBowlerWicket", "BowlerRun"]].apply(lambda x: '/'.join(map(str, x.values)), axis = 1)
bowler.rename(columns = {"bowler": "PlayerOfMatch"}, inplace = True)
bowler.head()

       ID PlayerOfMatch  IsBowlerWicket  BowlerRun BowlingFigure
0  335984   MF Maharoof               2         11          2/11
1  335986     DJ Hussey               1         35          1/35
2  335987     SR Watson               0         39          0/39
3  335990     YK Pathan               2         20          2/20
4  335992     SR Watson               2         20          2/20

In [ ]:
batter.merge(bowler, on=["ID", "PlayerOfMatch"], how = "outer").drop(columns = ["batsman_run", "IsBatsmanBall", "IsBowlerWicket", "BowlerRun"]).head()

       ID PlayerOfMatch BattingFigure BowlingFigure
0  335982   BB McCullum        158/73           NaN
1  335983    MEK Hussey        116/54           NaN
2  335984   MF Maharoof           NaN          2/11
3  335985    MV Boucher         39/19           NaN
4  335986     DJ Hussey         38/43          1/35