In [1]:
import plotly.express as px
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("../Datasets/social_media_engagement.csv")
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [3]:
df.nunique()

post_id            100
platform             3
post_type            5
post_time           99
likes               93
comments            85
shares              96
post_day             7
sentiment_score      3
dtype: int64

In [4]:
fig=px.bar(df,x="post_type",y="likes",width=500,height=500,title="Likes by Post Type")
# or
# fig=px.bar(x=df.post_type,y=df.likes)
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [5]:
fig=px.bar(df,x="post_type",y="likes",width=500,height=500,title="Likes by Post Type",text_auto=True)
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [6]:
fig=px.bar(df,x="post_type",y="likes",width=500,height=500,title="Likes by Post Type",color="platform")
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [7]:
fig=px.bar(df,x="post_type",y="likes",width=500,height=500,title="Likes by Post Type",color="platform",color_discrete_map={"Facebook":"blue","Instagram":"magenta","Twitter":"cyan"})
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [8]:
fig=px.bar(df,x="post_type",y="likes",width=900,height=800,title="Likes by Post Type",color="platform",color_discrete_sequence=["blue","magenta","cyan"])
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [9]:
fig=px.bar(df,x="post_type",y="likes",width=800,height=600,title="Likes by Post Type",color="comments")
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [10]:
fig=px.bar(df,x="post_type",y="likes",width=800,height=600,title="Likes by Post Type",color="comments",hover_data=["post_day","sentiment_score"])
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [11]:
fig=px.bar(df,y="post_type",x="likes",width=800,height=600,title="Likes by Post Type",color="comments",hover_data=["post_day","sentiment_score"],orientation="h")
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes",)
fig.show()

In [12]:
fig=px.bar(df,y="post_type",x="likes",width=800,height=600,title="Likes by Post Type",color="comments",hover_data=["post_day","sentiment_score"],orientation="h",text="likes")
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes",)
fig.show()

In [13]:
fig=px.bar(df,x="post_type",y="likes",width=800,height=900,title="Likes by Post Type",color="platform",
           hover_data=["post_day","sentiment_score"],pattern_shape="sentiment_score")
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [14]:
fig=px.bar(df,x="post_type",y=["likes","shares","comments"],width=800,height=900,title="Engagement by Post Type")
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [15]:
fig=px.bar(df,x="post_type",y=["likes","shares","comments"],width=800,height=900,title="Engagement by Post Type",barmode="stack")
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [16]:
fig=px.bar(df,x="post_type",y=["likes","shares","comments"],width=800,height=900,title="Engagement by Post Type",barmode="group")
fig.update_layout(xaxis_title="Post Type",yaxis_title="Likes")
fig.show()

In [17]:
df["comments_n"]=df["comments"]*-1

In [18]:
fig=px.bar(df,x="post_id",y=["comments_n","shares"],barmode="relative")
fig.show()

In [19]:
fig=px.scatter(df,x="shares",y="likes",color="platform",symbol="platform")
fig.show()

In [20]:
fig=px.scatter(df,x="shares",y="likes",color="platform",symbol="post_type")
fig.show()

In [21]:
fig=px.scatter(df,x="comments",y="likes",size="shares")
fig.show()

In [22]:
fig=px.scatter(df,x="comments",y="likes",size="shares",color="post_type")
# color-->group chart
# size-->bubble chart
fig.show()

In [23]:
fig=px.scatter(df,x="comments",y="likes",size="shares",color="post_type",facet_row="post_day",facet_col="sentiment_score")

fig.show()

In [24]:
fig=px.scatter_3d(df,x="likes",y="comments",z="shares",color="platform")
fig.show()

In [25]:
fig=px.scatter_matrix(df,dimensions=["likes","comments","shares"],color="platform",width=1100,height=900,size="shares")
fig.show()

In [28]:
df1=df.groupby("platform",as_index=False)[["likes","comments","shares"]].sum()
df1

    platform   likes  comments  shares
0   Facebook   86392      7965   15180
1  Instagram  107994      8368   18906
2    Twitter   43795      3933    7479

In [34]:
fig=px.pie(df1,names="platform",values="likes",color_discrete_sequence=["pink","beige","lightblue"])
fig.update_traces(textinfo="percent+label",textposition="outside",pull=[0,0,0.2])
fig.show()

In [38]:
fig=px.line(df,x="post_id",y="likes",color="platform",markers=True)
fig.show()

In [39]:
pd.get_dummies(df)

,post_id,likes,comments,shares,comments_n,platform_Facebook,platform_Instagram,platform_Twitter,post_type_carousel,post_type_image,...,post_day_Friday,post_day_Monday,post_day_Saturday,post_day_Sunday,post_day_Thursday,post_day_Tuesday,post_day_Wednesday,sentiment_score_negative,sentiment_score_neutral,sentiment_score_positive
0,1,2121,474,628,-474,True,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
1,2,3660,432,694,-432,True,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
2,3,4955,408,688,-408,False,True,False,False,False,...,False,False,False,False,False,True,False,True,False,False
3,4,1183,90,187,-90,False,False,True,False,True,...,False,False,False,False,True,False,False,True,False,False
4,5,3499,247,286,-247,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,36,294,911,-294,False,True,False,True,False,...,False,False,False,False,False,False,True,False,False,True
96,97,314,108,458,-108,False,False,True,False,False,...,True,False,False,False,False,False,False,False,True,False
97,98,229,179,38,-179,False,False,True,False,False,...,False,False,True,False,False,False,False,False,False,True
98,99,5000,500,204,-500,False,True,False,False,False,...,True,False,False,False,False,False,False,False,False,True
99,100,4483,357,25,-357,False,True,False,False,True,...,False,False,False,False,False,True,False,False,True,False